### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by thisfardi** [rashidsiregar28/chikabot#1]
mohon bantuannya perbaiki QR Code terlalu cepat request baru sehingga ketika di scan tidak berhasil.
terima kasih

**Comment by thisfardi** [comment]
waktu di scan langsung koneksi terputus.
![image](https://user-images.githubusercontent.com/38723240/143422303-59044450-85c0-4a79-b3a3-af93e2c0a8ab.png)

**Comment by rashidsiregar28** [comment]
Qr baileys md itu biasanya tahan sampai 1 menit ngga discan bang, udh fix join md ga? Kok langsung logout..

**Comment by Dvnz99** [comment]
> waktu di scan langsung koneksi terputus. ![image](https://user-images.githubusercontent.com/38723240/143422303-59044450-85c0-4a79-b3a3-af93e2c0a8ab.png)

join wa web md blm bg?

**Comment by thisfardi** [comment]
solved untuk scan qr pak, skrng mslhnya bgni pak.
mohon solusinya pak terima kasih
![image](https://user-images.githubusercontent.com/38723240/143515253-b7a9feb1-fed2-4824-9c06-5587c9690ef8.png)

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/143516723-161e4850-3f41-4fb9-bb54-0c65d3d37a36.png)

**Comment by rashidsiregar28** [comment]
Kalo baru join md,emang gitu, kalo axios lupa import, fix [disini](https://github.com/rashidsiregar28/chikabot/blob/9f2ba0559f8e5fb999d04f2b6ca1729d8ba28ea4/message/chika.js#L12)

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/143519633-8482209d-8542-4ffe-a015-fd3f108ee31d.png)
oalah, trus kalo gni gmn pak solusinya ?

**Comment by rashidsiregar28** [comment]
> ![image](https://user-images.githubusercontent.com/38723240/143519633-8482209d-8542-4ffe-a015-fd3f108ee31d.png) oalah, trus kalo gni gmn pak solusinya ?

Multi device di hp lu blum stabil

**Comment by thisfardi** [comment]
> 

gua keluarin pak di wanya, mau gua scan qr lagi keterangannya bgtu

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/143521017-2818fef9-08c3-4c9a-9e6d-331e716697a5.png)
barusan gua update lagi source nya error pak gk bisa jalan.

**Comment by rashidsiregar28** [comment]
Yo wes jangan di komplain mulu, lagian md blum stabil, kalo emang ga connect, hapus session, scan ulang, hapus lagi, scan lagi ampe masuk

**Comment by thisfardi** [comment]
> Yo wes jangan di komplain mulu, lagian md blum stabil, kalo emang ga connect, hapus session, scan ulang, hapus lagi, scan lagi ampe masuk

hapus sessionnya dmn pak ?

**Comment by thisfardi** [comment]
maaf pak bkn maksd komplain cm ngeluh :V

**Comment by rashidsiregar28** [comment]
> maaf pak bkn maksd komplain cm ngeluh :V

Ngeluh ke lord adi sana aowokaowk
Gweh close yak

**Comment by KiZakiXD** [comment]
mengclose
